# Generated by Django 3.2.6 on 2021-11-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Subject', models.CharField(blank=True, max_length=100)),
                ('Phone', models.IntegerField()),
                ('Message', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Proj_cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_Url', models.URLField(default=None, max_length=1000)),
                ('Url', models.URLField(blank=True, max_length=500)),
                ('Title', models.CharField(blank=True, max_length=30)),
                ('Sub_title', models.CharField(blank=True, max_length=30)),
                ('Select_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_app.proj_cate')),
            ],
        ),
    ]
