# Generated by Django 3.2.6 on 2021-11-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Subject', models.CharField(blank=True, max_length=100)),
                ('Phone', models.IntegerField(default=None)),
                ('Message', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Images')),
                ('Url', models.URLField(blank=True, max_length=500)),
                ('Title', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
