# Generated by Django 3.2.6 on 2021-11-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Sub_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
