# Generated by Django 3.2.6 on 2021-11-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_info',
            name='Phone',
        ),
    ]
