# Generated by Django 3.2.6 on 2021-11-14 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20211113_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proj_cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='Select_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_app.proj_cate'),
        ),
    ]
