# Generated by Django 3.2.6 on 2021-11-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20211113_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='Image',
        ),
        migrations.AddField(
            model_name='projects',
            name='Image_Url',
            field=models.URLField(default=None, max_length=1000),
        ),
    ]
